
export const BASE_API = "https://yuheng.gzisv.com";
// export const BASE_API = "https://miniprogram.yuhengdaijia.com";

export const HTTP_STATUS = {
  SUCCESS: 200,
  CLIENT_ERROR: 400,
  AUTHENTICATE: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  SERVER_ERROR: 500,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504
};

export const ERROR_TYPE_CODE = {
  PARAMS_ERROR: 401,
  FREQUENT_REQUEST: 402,
  EXPIRED_SESSION: 409,

  SERVER_ERROR: 501,

  NAME_EXIST: 601,
  SECURITY_CHECK_FAILED: 609,

  NOT_LOGIN: 901,
  LOGIN_ERROR: 902,
  USER_NOT_EXIST: 903,
  USER_EXIST: 904,
  USER_UNAUTHORIZED_MOBILE_NUMBER: 905,

  //业务错误码
  MANAGER_ERROR: 1001,
  PERMISSION_ERROR: 403,
  NON_BIND: 801,
  FILE_OVERSIZE: 608
};

export const ERROR_TYPE_MAP = {
  [ERROR_TYPE_CODE.PARAMS_ERROR]: "请求参数不正确",
  [ERROR_TYPE_CODE.FREQUENT_REQUEST]: "请求频繁",
  [ERROR_TYPE_CODE.EXPIRED_SESSION]: "登录态过期",

  [ERROR_TYPE_CODE.SERVER_ERROR]: "服务器处理错误，请稍后重试",

  [ERROR_TYPE_CODE.NAME_EXIST]: "用户已绑定公众号",
  [ERROR_TYPE_CODE.SECURITY_CHECK_FAILED]: "请求被安全检查拦截",

  [ERROR_TYPE_CODE.NOT_LOGIN]: "用户未登录",
  [ERROR_TYPE_CODE.LOGIN_ERROR]: "登陆失败",
  [ERROR_TYPE_CODE.USER_NOT_EXIST]: "用户未注册",
  [ERROR_TYPE_CODE.USER_EXIST]: "用户已注册",
  [ERROR_TYPE_CODE.USER_UNAUTHORIZED_MOBILE_NUMBER]: "用户未授权手机号码",

  [ERROR_TYPE_CODE.MANAGER_ERROR]: "系统处理错误",
  [ERROR_TYPE_CODE.PERMISSION_ERROR]: '用户无权限操作',
  [ERROR_TYPE_CODE.NON_BIND]: '还没绑定公众号',
  [ERROR_TYPE_CODE.FILE_OVERSIZE]: '文件过大',
};












"还没绑定公众号";
"文件过大";